[workspace]
members = [
    "cep18",
    "cep18-test-contract",
    "cep18-test",
    "tests",
]
default-members = [
    "cep18",
    "cep18-test-contract",
    "cep18-test",
    "tests",
]

[profile.release]
codegen-units = 1
lto = true
