[package]
name = "contract"
version = "0.1.1"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
doctest = false
test = false
bench = false

[dependencies]
casperlabs-contract = "0.4.0"
casperlabs-types = "0.4.0"
logic = { path = "../logic", default-features = false }

[features]
default = ["casperlabs-contract/std", "casperlabs-types/std"]
