[package]
name = "cep18-test-contract"
version = "0.2.1"
authors = ["Michał Papierski <michal@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "cep18_test_contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = "=1.4.4"
casper-types = "=1.6.0"
